#!/bin/bash

#made by Eric Johnson

#{
logDir=/sdCard/Logs
cd $logDir
echo "adding changes..."
echo
git add --ignore-removal . 2>&1
echo
echo "commiting to master..."
echo
git commit -m "new logs pushed on `date`" 2>&1
echo
echo "pushing logs..."
echo
git push 2>&1
echo
echo "removing logs..."
echo
rm *.log
rm *.avi
echo
echo "done."
echo
#} >> /sdCard/Logs/logPusher.log

